spring:
  application:
    name: superpoint
  datasource:
    url: jdbc:mysql://localhost:3204/superpoint?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: superpoint
    password: HbPaMri6j7eGDEbi
server:
  port: 7744
  shutdown: immediate